StephanieJay/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StephanieJay.Models;

namespace StephanieJay.Controllers
{
    public class ContactController : Controller
    {
        //
        // GET: /Contact/

        public ActionResult Index()
        {
            return View(new ContactViewModel());
        }

        [HttpPost]
        public ActionResult Index(ContactViewModel contactVM)
        {
            if (!ModelState.IsValid)
            {
                return View(contactVM);
            }

            var contact = new Contact
            {
                From = contactVM.From,
                ContactVia = contactVM.ContactVia,
                Message = contactVM.Message
            };

            new Email().Send(contact);

            return RedirectToAction("ContactConfirm");
        }

        public ActionResult ContactConfirm()
        {
            return View();
        }
    }
}

StephanieJay/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StephanieJay.Controllers
{
    public class GalleryController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

StephanieJay/Controllers/VenuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StephanieJay.Controllers
{
    public class VenuesController : Controller
    {
        //
        // GET: /Venues/

        public ActionResult Index()
        {
            return View();
        }

    }
}

StephanieJay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @RenderSection("HeaderJS", false)

    <link href="@Url.Content("~/CSS/reset.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/CSS/tweetScroll.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/CSS/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/CSS/style.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/CSS/datepicker.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.6.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/stratus.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/ultimate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-carousel.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-transition.js")" type="text/javascript"></script>
    <script src="http://cufon.shoqolate.com/js/cufon-yui.js" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/yanone-kaffeesatz.cufonfonts.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.dotdotdot-1.5.1.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.parss.uncompressed.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $.stratus({
                align: 'top',
                theme: 'http://stratus.sc/themes/dark.css',
                color: '888888',
                links: 'https://soundcloud.com/stephaniejay/'
            });

            function autoScroll() {
                var itemHeight = $('#tweetlist li').outerHeight();
                /* calculte how much to move the scroller */
                var moveFactor = parseInt($('#tweetlist').css('top')) + itemHeight;
                /* animate the carousel */
                $('#tweetlist').animate({ 'top': moveFactor }, 'slow', 'linear', function () {
                    /* put the last item before the first item */
                    $("#tweetlist li:first").before($("#tweetlist li:last"));
                    /* reset top position */
                    $('#tweetlist').css({ 'top': -itemHeight });
                });
            };

            /* make the carousel scroll automatically when the page loads */
            var moveScroll = setInterval(autoScroll, 10000);
     
            $.getJSON('http://search.twitter.com/search.json?rpp=75&callback=?&q=%40djstephaniejay', function (data) {
                for (var i = 0; i < data.results.length; i++) {
                    var tweeter = data.results[i].from_user;
                    var tweetText = data.results[i].text;
                    var tweetText = tweetText.substring(0, 139);
                    tweetText = tweetText.replace(/http:\/\/\S+/g, '<a href="$&" target="_blank">$&</a>');
                    tweetText = tweetText.replace(/(@@)(\w+)/g, ' $1<a href="http://twitter.com/$2" target="_blank">$2</a>');
                    tweetText = tweetText.replace(/(#)(\w+)/g, ' $1<a href="http://search.twitter.com/search?q=%23$2" target="_blank">$2</a>');
                    $('#tweetlist').append('<li class="tweet box-item"><div class="tweetImage"><a href="http://twitter.com/' + tweeter + '" target="_blank"><img src="' + data.results[i].profile_image_url + '" width="48" border="0" /></a></div><div class="tweetBody">' + tweetText + '</div></li>');
                }
            });

            /*Triple Dots!*/
            $(".box .box-item").dotdotdot();

            /*Carousel*/
            $('.carousel').carousel({ interval: 10000 });
        });

        Cufon.replace('.box h2, .box h3, h2, #nav a, .parss-title a', { fontFamily: 'Yanone Kaffeesatz Regular', hover: true });

    </script>   
</head>
<body>

    <div id="logo"></div>

    <div id="nav-wrap">
        <div id="nav">
            @Html.ActionLink("HOME", "Index", "Home", new { area = ""}, null)
            @Html.ActionLink("GIGS", "Index", "Gigs", new { area = "" }, null)
            @Html.ActionLink("GALLERY", "Index", "Gallery", new { area = "" }, null)
@*            @Html.ActionLink("Mixes", "Index", "Mixes")
*@          @Html.ActionLink("BIO", "Index", "Bio", new { area = "" }, null)
            @Html.ActionLink("CONTACT", "Index", "Contact", new { area = "" }, null)
            @Html.ActionLink("VENUES", "Index", "Venues", new { area = "" }, null)
        </div>
    </div>
    <div id="main-content">
        <div class="container">
            @RenderBody()
        </div>
    </div>
    <div id="footer">
    <div class="container">
        <div class="row">
            <div class="span6">
                <h2>SOCIAL.</h2>
                <div class="row">
                    <div class="span1">
                        <img alt="twitter" src="../../Images/Icons/twitter-32x32.png" />
                        <a href="http://www.twitter.com/djstephaniejay">twitter</a>
                    </div>
                    <div class="span1">
                        <img alt="facebook" src="../../Images/Icons/facebook-32x32.png" />
                        <a href="http://www.facebook.com/djstephaniej">facebook</a>
                    </div>
                    <div class="span1">
                        <img alt="mixcloud" src="../../Images/Icons/mixcloud-32x32.png" />
                        <a href="http://www.mixcloud.com/stephaniejay">mixcloud</a>
                    </div>
                    <div class="span1">
                        <img alt="soundcloud" src="../../Images/Icons/soundcloud-32x32.png" />
                        <a href="http://www.soundcloud.com/stephaniejay">soundcloud</a>
                    </div>
                    <div class="span1">
                        <img alt="soundcloud" src="../../Images/Icons/beatport-32x32.png" />
                        <a href="http://www.beatport.com/artist/stephanie-jay/194092">beatport</a>
                    </div>
                </div><!-- End Row -->
            </div><!-- End Span6 -->
        </div>
        <div class="row" style="margin-top:60px;">
            <div class="span12">
                <div class="row-fluid">
                    <div class="span9"></div>
                    <div class="span2">
                        <img alt="Stephanie Jay" src="../../Images/Content/logo.png" />
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span9"></div>
                    <div class="span3">
                        <span>All rights reserved © @DateTime.Now.Year Stephanie Jay.</span>
                    </div>
                </div>  
            </div>
        </div>
    </div>
    </div>
</body>
</html>