StephanieJay/Controllers/WelcomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using StephanieJay.Models;
using System.Net;
using RSS;
using System.Web.Configuration;
using StephanieJay.Classes;

namespace StephanieJay.Controllers
{
    [Authorize(Users="Stephanie")]
    public class WelcomeController : Controller
    {
        private readonly string _xmlPath;

        public WelcomeController()
        {
            _xmlPath = System.Web.HttpContext.Current.Server.MapPath(WebConfigurationManager.AppSettings["WelcomeMessage"]);
        }

        //GET: /Admin/Welcome
        public ActionResult Index()
        {
            var welcome = Xml<WelcomeMessage>.Load(System.Web.HttpContext.Current.Server.MapPath(WebConfigurationManager.AppSettings["WelcomeMessage"]));
            return View("/Views/Admin/Welcome/Index.cshtml", welcome);
        }

        //POST: /Admin/Welcome
        [HttpPost]
        public ActionResult Index(WelcomeMessage message)
        {
            Xml<WelcomeMessage>.Save(_xmlPath, message);
            return View("/Views/Admin/Welcome/Index.cshtml", message);
        }
    }
}

StephanieJay/Areas/Admin/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Admin";
}
<div class="row">
    <div class="span12 box">
        <h2>Admin</h2>
        <ul class="box-item-bag">
            <li class="box-item">
                @Html.ActionLink("Edit Welcome Message", "Index", "Welcome")
            <li class="box-item">
                @Html.ActionLink("Edit News", "Index", "News")
            </li>
            <li class="box-item">
                @Html.ActionLink("Edit Bio", "Index", "Bio")
            </li>
            <li class="box-item">
                @Html.ActionLink("Edit Gigs", "Index", "Gigs")
            </li>
        </ul>
    </div>
</div>